---
- name: Install Jenkins with HTTPS using Certbot
  hosts: jenkins
  become: true

  vars:
    java_packages:
      # - openjdk-17-jdk
      - openjdk-21-jdk
    jenkins_http_port: 8080
    jenkins_hostname: mydomain.com
    certbot_create_if_missing: true
    certbot_admin_email: mymail@example.com
    certbot_auto_renew: true
    certbot_certs:
      - email: mymail@example.com
        domains:
          - mydomain.com
        webroot: /var/lib/jenkins

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
    - geerlingguy.certbot

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure Nginx for Jenkins HTTPS reverse proxy
      copy:
        dest: /etc/nginx/sites-available/jenkins
        content: |
          server {
              listen 80;
              server_name mydomain.com;
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              server_name mydomain.com;

              ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;

              location / {
                  proxy_pass http://localhost:8080;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Enable Jenkins Nginx config
      file:
        src: /etc/nginx/sites-available/jenkins
        dest: /etc/nginx/sites-enabled/jenkins
        state: link

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
